//! The actual linker itself,
//! this runs all the linking and remapping
//! for all the files down into one

use std::{
    collections::{HashMap, HashSet},
    fmt::Display,
};

/// Errors that can occur during the linking process
pub struct LinkerError {
    kind: LinkerErrorKind,
    line: usize,
    file: String,
}

/// All kinds of errors that can occur during the linking process
pub enum LinkerErrorKind {
    /// There was an undefined name that could not be remapped
    UndefinedName { name: String },

    /// There was a file that did not declare its namspace
    UndeclaredNamespace { file: String },

    /// There was a duplicate namespace found, this is not allowed.
    DuplicateNamespace {
        // The namespace
        namespace: String,

        // These two files have duplicate namespaces
        file_a: String,
        file_b: String,
    },

    /// More than one namespace declared in a file!
    MoreThanOneNamespace { file: String },

    /// A file required a namespace that was not included
    /// in the linking process
    NamespaceNotFound {
        namespace: String,
        file_requires: String,
    },
}

/// A namespace, essentially just a string for
/// remapping things imported
#[derive(PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone)]
pub struct NameSpace(String);

/// The actual linker itself, this maps a set
/// of input Boson3 source files that import eachother
/// out into one final Boson3 file
pub struct Linker {
    sources: Vec<LinkableFile>,

    /// The output linked file
    output: Vec<String>,

    /// All declared namespaces
    namespaces: HashSet<NameSpace>,

    // Mapping of the name space to the filename that declared it
    namespace_map: HashMap<NameSpace, String>,

    // The global remapped valid symbols
    valid_symbols: HashSet<String>,
}

/// The linkable file, this contains
/// a file that can be linked together with other files
///
/// The file contents here are the actual contents of
/// the file under `file_name`.
///
/// The `file_name` should just be the absoslute file name
/// of this file with the extension.
pub struct LinkableFile {
    pub file_contents: String,
    pub file_name: String,
    pub full_file_name: String,

    // The namespace for the file, this is found by the linker
    // and should be set to None by default.
    pub namespace: Option<NameSpace>,

    // This is built after the top level names have been remapped
    // for this linkable file
    pub remap_maps: Option<RemapMaps>,
}

/// The Remap-maps for a file which tells how the linker
/// should remap everything, this is built by remapping all
/// the top-level names using the namespace of the file
pub struct RemapMaps {
    // @global remap
    pub globals_map: HashMap<String, String>,

    // @fn remap
    pub function_map: HashMap<String, String>,

    // @capability remap
    pub capability_map: HashMap<String, String>,

    // @object remap
    pub object_map: HashMap<String, String>,

    // @macro remap
    pub macro_map: HashMap<String, String>,
}

impl Linker {
    /// Creates a new linker that will link all of these source files together
    pub fn new(sources: Vec<LinkableFile>) -> Self {
        Self {
            sources,
            output: Vec::new(),
            namespaces: HashSet::new(),
            namespace_map: HashMap::new(),
            valid_symbols: HashSet::new(),
        }
    }

    /// Links all the files together, returns the outputted linked
    /// together `Boson3` file.
    pub fn link(mut self) -> Result<String, Vec<LinkerError>> {
        self.collect_namespaces().map_err(|err| vec![err])?;
        self.check_all_requires()?;
        self.remap_all_top_levels()?;
        self.remap_all_instructions()?;

        // Combine all files together into the output
        for file in self.sources {
            self.output.push(format!(
                "// Linked namespace `{}` from file `{}`\n",
                file.namespace.expect("namespace to be resolved").0,
                file.full_file_name.clone()
            ));
            self.output.push(file.file_contents);
            self.output.push("\n\n".to_string());
        }

        Ok(self.output.join(""))
    }

    /// Remap all of the top-level names in all files
    fn remap_all_top_levels(&mut self) -> Result<(), Vec<LinkerError>> {
        // The full remap-map generated by this phase
        let mut remap_map = std::mem::take(&mut self.valid_symbols);
        let mut errors = Vec::new();

        // Remap each file
        for file in &mut self.sources {
            if let Err(this_errors) = Linker::remap_top_levels(&mut remap_map, file) {
                errors.extend(this_errors);
            }
        }

        // Put back for remap instructions
        self.valid_symbols = remap_map;

        if errors.is_empty() {
            return Ok(());
        }

        Err(errors)
    }

    /// Remap all of the instructions in all files
    fn remap_all_instructions(&mut self) -> Result<(), Vec<LinkerError>> {
        // The full valid map for matching on each source file
        let valid_map = std::mem::take(&mut self.valid_symbols);
        let mut errors = Vec::new();

        // Remap each file's instructions
        for file in &mut self.sources {
            if let Err(this_errors) = Linker::remap_instructions(&valid_map, file) {
                errors.extend(this_errors);
            }
        }

        // Put back for fun
        self.valid_symbols = valid_map;

        if errors.is_empty() {
            return Ok(());
        }

        Err(errors)
    }

    /// Remaps all the instructions in a file
    ///
    /// This assumes the remap map was already defined in the file
    fn remap_instructions(
        valid_symbols: &HashSet<String>,
        file: &mut LinkableFile,
    ) -> Result<(), Vec<LinkerError>> {
        // The new file contents after remapping
        let mut output = Vec::new();
        let mut errors = Vec::new();

        // The current parameters of the macro body we are walking if any,
        // we need to NOT remap macro params inserted in-line and stuff so this is for that!
        let mut macro_params: Option<Vec<String>> = None;

        // Remap-maps
        let remap_maps = file
            .remap_maps
            .as_ref()
            .expect("expected remap maps to already have been gathered for file");

        let globals_map = &remap_maps.globals_map;
        let function_map = &remap_maps.function_map;
        let capability_map = &remap_maps.capability_map;
        let object_map = &remap_maps.object_map;
        let macro_map = &remap_maps.macro_map;

        // The pass, remap all instructions now with names
        for (line_number, line) in file.file_contents.lines().enumerate() {
            let line_number = line_number + 1;

            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            match tokens.as_slice() {
                // @macro <name> (<param>, ...) opens a macro body,
                // we should be careful to not replace any of the params with remapped things
                ["@macro", _, params @ ..] => {
                    let param_names = params
                        .join(" ")
                        .replace(['(', ')', ','], " ")
                        .split_whitespace()
                        .map(|name| name.to_string())
                        .collect();
                    macro_params = Some(param_names);
                    output.push(tokens.join(" "));
                }

                // @end closes a macro body
                ["@end", ..] => {
                    macro_params = None;
                    output.push(tokens.join(" "));
                }

                // globals remapping
                [
                    op @ ("store.global" | "load.global" | "log" | "stg"),
                    global,
                ] => {
                    // Do not overwrite macro params!
                    if let Some(params) = &macro_params {
                        if params.iter().any(|param| param == global) {
                            output.push(format!("{op} {global}"));
                            continue;
                        }
                    }

                    // Get the name from the map, else test if its in the valid symbols map.
                    let new_global_name = match globals_map.get(*global).ok_or_else(|| {
                        LinkerErrorKind::UndefinedName {
                            name: global.to_string(),
                        }
                        .with_line(line_number, file.full_file_name.clone())
                    }) {
                        Ok(name) => name,
                        Err(error) => {
                            if valid_symbols.contains(*global) {
                                *global
                            } else {
                                errors.push(error);
                                continue;
                            }
                        }
                    };

                    push_out(
                        &file.full_file_name,
                        format!("{op} {new_global_name}"),
                        line_number,
                        &mut output,
                    );
                }

                // object remapping
                [op @ ("object.new" | "onw"), object] => {
                    // Do not overwrite macro params!
                    if let Some(params) = &macro_params {
                        if params.iter().any(|param| param == object) {
                            output.push(format!("{op} {object}"));
                            continue;
                        }
                    }

                    let new_object_name = match object_map.get(*object).ok_or_else(|| {
                        LinkerErrorKind::UndefinedName {
                            name: object.to_string(),
                        }
                        .with_line(line_number, file.full_file_name.clone())
                    }) {
                        Ok(name) => name,
                        Err(error) => {
                            if valid_symbols.contains(*object) {
                                *object
                            } else {
                                errors.push(error);
                                continue;
                            }
                        }
                    };

                    push_out(
                        &file.full_file_name,
                        format!("{op} {new_object_name}"),
                        line_number,
                        &mut output,
                    );
                }

                [op @ ("object.set" | "ost" | "object.get" | "ogt"), object] => {
                    // Do not overwrite macro params! (they dont have dots anyway)
                    if let Some(params) = &macro_params {
                        if params.iter().any(|param| param == object) {
                            output.push(format!("{op} {object}"));
                            continue;
                        }
                    }

                    // We the field and object name (2 elements)
                    let split_access = object.split(".").collect::<Vec<_>>();

                    // Fail in lowering.
                    if split_access.len() != 2 {
                        output.push(split_access.join(" "));
                        continue;
                    }

                    let object_name = split_access[0];
                    let field = split_access[1];

                    let new_object_name = match object_map.get(object_name).ok_or_else(|| {
                        LinkerErrorKind::UndefinedName {
                            name: object_name.to_string(),
                        }
                        .with_line(line_number, file.full_file_name.clone())
                    }) {
                        Ok(name) => name,
                        Err(error) => {
                            if valid_symbols.contains(object_name) {
                                object_name
                            } else {
                                errors.push(error);
                                continue;
                            }
                        }
                    };

                    push_out(
                        &file.full_file_name,
                        format!("{op} {new_object_name}.{field}"),
                        line_number,
                        &mut output,
                    );
                }

                // function remapping
                [op @ ("call" | "cal" | "tail.call" | "tcl"), function] => {
                    // Do not overwrite macro params!
                    if let Some(params) = &macro_params {
                        if params.iter().any(|param: &String| param == function) {
                            output.push(format!("{op} {function}"));
                            continue;
                        }
                    }

                    let new_function_name = match function_map.get(*function).ok_or_else(|| {
                        LinkerErrorKind::UndefinedName {
                            name: function.to_string(),
                        }
                        .with_line(line_number, file.full_file_name.clone())
                    }) {
                        Ok(name) => name,
                        Err(error) => {
                            if valid_symbols.contains(*function) {
                                *function
                            } else {
                                errors.push(error);
                                continue;
                            }
                        }
                    };

                    push_out(
                        &file.full_file_name,
                        format!("{op} {new_function_name}"),
                        line_number,
                        &mut output,
                    );
                }

                // capabilities remapping
                [op @ ("call.cap" | "cap"), capability] => {
                    // Do not overwrite macro params!
                    if let Some(params) = &macro_params {
                        if params.iter().any(|param| param == capability) {
                            output.push(format!("{op} {capability}"));
                            continue;
                        }
                    }

                    let new_capability_name =
                        match capability_map.get(*capability).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: capability.to_string(),
                            }
                            .with_line(line_number, file.full_file_name.clone())
                        }) {
                            Ok(name) => name,
                            Err(error) => {
                                if valid_symbols.contains(*capability) {
                                    *capability
                                } else {
                                    errors.push(error);
                                    continue;
                                }
                            }
                        };

                    push_out(
                        &file.full_file_name,
                        format!("{op} {new_capability_name}"),
                        line_number,
                        &mut output,
                    );
                }

                // A macro invocation remapping
                [invocation, args @ ..] if invocation.starts_with("!") => {
                    // The name of the macro
                    let name = invocation.strip_prefix("!").unwrap_or(*invocation);

                    // Find new remapped name
                    let new_macro_name = match macro_map.get(name).ok_or_else(|| {
                        LinkerErrorKind::UndefinedName {
                            name: name.to_string(),
                        }
                        .with_line(line_number, file.full_file_name.clone())
                    }) {
                        Ok(name) => name,
                        Err(error) => {
                            if valid_symbols.contains(name) {
                                name
                            } else {
                                errors.push(error);
                                continue;
                            }
                        }
                    };

                    // Rebuild new macro invocation with all the arguments
                    let mut rebuilt = vec![format!("!{new_macro_name}")];
                    rebuilt.extend(args.iter().map(|token| token.to_string()));

                    push_out(
                        &file.full_file_name,
                        rebuilt.join(" "),
                        line_number,
                        &mut output,
                    );
                }

                // Directives cant have @loc attached
                directive if directive.iter().any(|tok| tok.starts_with("@")) => {
                    output.push(directive.join(" "))
                }

                // Non-remappable things
                other => push_out(
                    &file.full_file_name,
                    other.join(" "),
                    line_number,
                    &mut output,
                ),
            }
        }

        file.file_contents = output.join("\n");

        if errors.is_empty() {
            return Ok(());
        }

        Err(errors)
    }

    /// Remaps all the top-level names in a file
    ///
    /// This assumes namespace was already defined in the file
    fn remap_top_levels(
        valid_map: &mut HashSet<String>,
        file: &mut LinkableFile,
    ) -> Result<(), Vec<LinkerError>> {
        // The new file contents after remapping
        let mut output = Vec::new();
        let mut errors = Vec::new();

        // Remap-maps
        let mut globals_map = HashMap::new();
        let mut function_map = HashMap::new();
        let mut capability_map = HashMap::new();
        let mut object_map = HashMap::new();
        let mut macro_map = HashMap::new();

        let file_namespace = file
            .namespace
            .clone()
            .expect("expected namespace to already have been gathered for file")
            .0;

        // First pass, gather all renamed elements
        for line in file.file_contents.lines() {
            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            match tokens.as_slice() {
                // @global <name>
                ["@global", name] => {
                    let remapped = format!("{}::{}", file_namespace, name);
                    globals_map.insert(name.to_string(), remapped);
                }

                // @fn <name>
                ["@fn", name, ..] => {
                    let remapped = format!("{}::{}", file_namespace, name);
                    function_map.insert(name.to_string(), remapped);
                }

                // @object <name>
                ["@object", name, ..] => {
                    let remapped = format!("{}::{}", file_namespace, name);
                    object_map.insert(name.to_string(), remapped);
                }

                // @capability <name>
                ["@capability", name, ..] => {
                    let remapped = format!("{}::{}", file_namespace, name);
                    capability_map.insert(name.to_string(), remapped);
                }

                // @macro <name> (args)
                ["@macro", name, ..] => {
                    let remapped = format!("{}::{}", file_namespace, name);
                    macro_map.insert(name.to_string(), remapped);
                }

                // Non-remappable things
                _ => {}
            }
        }

        // Second pass, remap everything now with gathered names
        for (line_number, line) in file.file_contents.lines().enumerate() {
            let line_number = line_number + 1;

            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                output.push(String::new());
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            match tokens.as_slice() {
                // These all have name as first arg and need to be remapped.
                remap_directive
                    if remap_directive[0].starts_with("@capability")
                        || remap_directive[0].starts_with("@object")
                        || remap_directive[0].starts_with("@global")
                        || remap_directive[0].starts_with("@fn")
                        || remap_directive[0].starts_with("@entry")
                        || remap_directive[0].starts_with("@macro") =>
                {
                    // ???, let another phase handle
                    if remap_directive.len() < 2 {
                        output.push(remap_directive.join(" "));
                        continue;
                    }

                    let remap_type = remap_directive[0];
                    let name = remap_directive[1];

                    // Map to the remapped name for this.
                    let remapped_name = match remap_type {
                        "@capability" => capability_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number, file.full_file_name.clone())
                        }),

                        "@object" => object_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number, file.full_file_name.clone())
                        }),

                        "@global" => globals_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number, file.full_file_name.clone())
                        }),

                        "@fn" => function_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number, file.full_file_name.clone())
                        }),

                        "@macro" => macro_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number, file.full_file_name.clone())
                        }),

                        "@entry" => function_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number, file.full_file_name.clone())
                        }),

                        _ => unreachable!(),
                    };

                    // Build errors
                    let remapped_name = match remapped_name {
                        Ok(remapped_name) => remapped_name,
                        Err(error) => {
                            output.push(String::new());
                            errors.push(error);
                            continue;
                        }
                    };

                    let mut new_directive = (*remap_directive).to_vec();
                    new_directive[1] = remapped_name;

                    output.push(new_directive.join(" ").to_string());
                }

                // These are already consumed earlier, we ignore them now
                consumed
                    if consumed[0].starts_with("@namespace")
                        || consumed[0].starts_with("@requires") =>
                {
                    output.push(String::new());
                }

                // We leave all other remapping to after all files have remapped their top level elements.
                other => output.push(other.join(" ")),
            }
        }

        file.file_contents = output.join("\n");

        // Add all these remapped symbols to the list of valid symbols
        valid_map.extend(
            globals_map
                .values()
                .cloned()
                .chain(capability_map.values().cloned())
                .chain(function_map.values().cloned())
                .chain(object_map.values().cloned())
                .chain(macro_map.values().cloned()),
        );

        // Build the remap-map for this file
        let remap_map = RemapMaps {
            globals_map,
            function_map,
            capability_map,
            object_map,
            macro_map,
        };

        file.remap_maps = Some(remap_map);

        if errors.is_empty() {
            return Ok(());
        }

        Err(errors)
    }

    /// Collects all the namespaces from all files and prevents duplicates.
    fn collect_namespaces(&mut self) -> Result<(), LinkerError> {
        for file in &mut self.sources {
            let namespace = Linker::find_namespace(file)?;

            // Check for duplicates
            if self.namespaces.contains(&namespace) {
                let original = self
                    .namespace_map
                    .get(&namespace)
                    .expect("expected namespace map and namespaces to be synced");
                return Err(LinkerErrorKind::DuplicateNamespace {
                    namespace: namespace.0,
                    file_a: original.clone(),
                    file_b: file.full_file_name.clone(),
                }
                .with_line(0, file.full_file_name.clone()));
            }

            // Add to maps
            self.namespaces.insert(namespace.clone());
            self.namespace_map
                .insert(namespace, file.full_file_name.clone());
        }

        Ok(())
    }

    /// Checks that all requires in all files are declared
    fn check_all_requires(&self) -> Result<(), Vec<LinkerError>> {
        let mut errors = Vec::new();

        // Check on each file that the requires are declared
        for file in &self.sources {
            if let Err(this_errors) = self.check_requires(file) {
                errors.extend(this_errors);
            }
        }

        if errors.is_empty() {
            return Ok(());
        }

        Err(errors)
    }

    /// Checks that all requires in a file are declared
    /// in the `namespaces`
    fn check_requires(&self, file: &LinkableFile) -> Result<(), Vec<LinkerError>> {
        let mut errors = Vec::new();

        for (line_number, line) in file.file_contents.lines().enumerate() {
            let line_number = line_number + 1;

            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            // Search for the requires directive in the file.
            if let ["@requires", namespace] = tokens.as_slice() {
                // Make sure the namespace is defined.
                if !self.namespaces.contains(&NameSpace(namespace.to_string())) {
                    errors.push(
                        LinkerErrorKind::NamespaceNotFound {
                            namespace: namespace.to_string(),
                            file_requires: file.full_file_name.clone(),
                        }
                        .with_line(line_number, file.full_file_name.clone()),
                    );
                }
            }
        }

        if errors.is_empty() {
            return Ok(());
        }

        Err(errors)
    }

    /// Finds the namespace used for a file
    fn find_namespace(file: &mut LinkableFile) -> Result<NameSpace, LinkerError> {
        let mut found_namespace = None;

        for line in file.file_contents.lines() {
            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            // Search for the namespace directive in the file.
            if let ["@namespace", namespace] = tokens.as_slice() {
                if found_namespace.is_none() {
                    let namespace = Some(NameSpace(namespace.to_string()));
                    found_namespace = namespace.clone();
                    file.namespace = namespace;
                } else {
                    return Err(LinkerErrorKind::MoreThanOneNamespace {
                        file: file.full_file_name.clone(),
                    }
                    .with_line(0, file.full_file_name.clone()));
                }
            }
        }

        found_namespace.ok_or_else(|| {
            LinkerErrorKind::UndeclaredNamespace {
                file: file.full_file_name.clone(),
            }
            .with_line(0, file.full_file_name.clone())
        })
    }
}

/// Strip a line comment from a line
fn strip_comment(line: &str) -> &str {
    if let Some(idx) = line.find("//") {
        &line[..idx]
    } else {
        line
    }
}

impl LinkerErrorKind {
    /// Adds a line to this `LinkerErrorKind` turning it into a
    /// `LinkerError`.
    pub fn with_line(self, line_number: usize, file: String) -> LinkerError {
        LinkerError {
            line: line_number,
            kind: self,
            file,
        }
    }
}

impl Display for LinkerErrorKind {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::UndefinedName { name } => {
                write!(f, "An undefined name was referenced: `{name}`")
            }
            Self::DuplicateNamespace {
                namespace,
                file_a,
                file_b,
            } => {
                write!(
                    f,
                    "The duplicate namespace `{namespace}` was declared in both `{file_a}` and `{file_b}`"
                )
            }
            Self::MoreThanOneNamespace { file } => {
                write!(
                    f,
                    "The file `{file}` contains more than one namespace declaration"
                )
            }
            Self::UndeclaredNamespace { file } => {
                write!(f, "The file `{file}` did not declare a namespace")
            }
            Self::NamespaceNotFound {
                namespace,
                file_requires,
            } => {
                write!(
                    f,
                    "The file `{file_requires}` @requires the namespace `{namespace}` but it was not found"
                )
            }
        }
    }
}

impl Display for LinkerError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "line `{}` in `{}`: {}", self.line, self.file, self.kind)
    }
}

/// Inserts a @loc directive at the current position with the source
/// being the original boson3 file
fn insert_loc(filename: &str, line_number: usize, output: &mut Vec<String>) {
    output.push(format!("@loc {} {line_number} 0", filename))
}

/// Pushes a line of output to the `output`, with a LOC attached.
///
/// This should be used for instructions, not directives.
fn push_out(file_name: &str, contents: String, line_number: usize, output: &mut Vec<String>) {
    insert_loc(file_name, line_number, output);
    output.push(contents);
}
