//! The actual linker itself,
//! this runs all the linking and remapping
//! for all the files down into one

use std::{
    collections::{HashMap, HashSet},
    fmt::Display,
};

/// Errors that can occur during the linking process
pub struct LinkerError {
    kind: LinkerErrorKind,
    line: usize,
}

/// All kinds of errors that can occur during the linking process
pub enum LinkerErrorKind {
    /// There was an undefined name that could not be remapped
    UndefinedName { name: String },

    /// There was a file that did not declare its namspace
    UndeclaredNamespace { file: String },

    /// There was a duplicate namespace found, this is not allowed.
    DuplicateNamespace {
        // The namespace
        namespace: String,

        // These two files have duplicate namespaces
        file_a: String,
        file_b: String,
    },

    /// More than one namespace declared in a file!
    MoreThanOneNamespace { file: String },

    /// A file required a namespace that was not included
    /// in the linking process
    NamespaceNotFound {
        namespace: String,
        file_requires: String,
    },
}

/// A namespace, essentially just a string for
/// remapping things imported
#[derive(PartialEq, Eq, PartialOrd, Ord, Hash, Debug, Clone)]
pub struct NameSpace(String);

/// The actual linker itself, this maps a set
/// of input Boson3 source files that import eachother
/// out into one final Boson3 file
pub struct Linker {
    sources: Vec<LinkableFile>,

    /// The output linked file
    output: Vec<String>,

    /// All declared namespaces
    namespaces: HashSet<NameSpace>,

    // Mapping of the name space to the filename that declared it
    namespace_map: HashMap<NameSpace, String>,

    // The global remapped valid symbols
    valid_symbols: HashSet<String>,
}

/// The linkable file, this contains
/// a file that can be linked together with other files
///
/// The file contents here are the actual contents of
/// the file under `file_name`.
///
/// The `file_name` should just be the absoslute file name
/// of this file with the extension.
#[derive(Hash)]
pub struct LinkableFile {
    pub file_contents: String,
    pub file_name: String,
    pub full_file_name: String,

    // The namespace for the file, this is found by the linker
    // and should be set to None by default.
    pub namespace: Option<NameSpace>,
}

impl Linker {
    /// Creates a new linker that will link all of these source files together
    pub fn new(sources: Vec<LinkableFile>) -> Self {
        Self {
            sources,
            output: Vec::new(),
            namespaces: HashSet::new(),
            namespace_map: HashMap::new(),
            valid_symbols: HashSet::new(),
        }
    }

    /// Links all the files together, returns the outputted linked
    /// together `Boson3` file.
    pub fn link(mut self) -> Result<String, Vec<LinkerError>> {
        self.collect_namespaces().map_err(|err| vec![err])?;
        self.check_all_requires()?;

        Ok(self.output.join("\n"))
    }

    /// Remap all of the top-level names in all files
    fn remap_all_top_levels(&mut self) -> Result<(), Vec<LinkerError>> {
        // The full remap-map generated by this phase
        let mut remap_map = std::mem::take(&mut self.valid_symbols);
        let mut errors = Vec::new();

        // Remap each file
        for file in &mut self.sources {
            if let Err(this_errors) = Linker::remap_top_levels(&mut remap_map, file) {
                errors.extend(this_errors);
            }
        }

        if errors.len() == 0 {
            return Ok(());
        }

        Err(errors)
    }

    /// Remaps all the top-level names in a file
    ///
    /// This assumes namespace was already defined in the file
    fn remap_top_levels(
        valid_map: &mut HashSet<String>,
        file: &mut LinkableFile,
    ) -> Result<(), Vec<LinkerError>> {
        // The new file contents after remapping
        let mut output = Vec::new();
        let mut errors = Vec::new();

        // Remap-maps
        let mut globals_map = HashMap::new();
        let mut function_map = HashMap::new();
        let mut capability_map = HashMap::new();
        let mut object_map = HashMap::new();

        let file_namespace = file
            .namespace
            .clone()
            .expect("expected namespace to already have been gathered for file")
            .0;

        // First pass, gather all renamed elements
        for line in file.file_contents.lines() {
            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            match tokens.as_slice() {
                // @global <name>
                ["@global", name] => {
                    let remapped = format!("{}::{}", file_namespace, name);
                    globals_map.insert(name.to_string(), remapped);
                }

                // @fn <name>
                function
                    if function.iter().any(|tok| tok.starts_with("@fn")) && function.len() < 2 =>
                {
                    let name = function[1];

                    let remapped = format!("{}::{}", file_namespace, name);
                    function_map.insert(name.to_string(), remapped);
                }

                // @object <name>
                object
                    if object.iter().any(|tok| tok.starts_with("@object")) && object.len() < 2 =>
                {
                    let name = object[1];

                    let remapped = format!("{}::{}", file_namespace, name);
                    object_map.insert(name.to_string(), remapped);
                }

                // @capability <name>
                capability
                    if capability.iter().any(|tok| tok.starts_with("@capability"))
                        && capability.len() < 2 =>
                {
                    let name = capability[1];

                    let remapped = format!("{}::{}", file_namespace, name);
                    capability_map.insert(name.to_string(), remapped);
                }

                // Non-remappable things
                _ => {}
            }
        }

        // Second pass, remap everything now with gathered names
        for (line_number, line) in file.file_contents.lines().enumerate() {
            let line_number = line_number + 1;

            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            match tokens.as_slice() {
                // These all have name as first arg and need to be remapped.
                remap_directive
                    if remap_directive[0].starts_with("@capability")
                        || remap_directive[0].starts_with("@object")
                        || remap_directive[0].starts_with("@global")
                        || remap_directive[0].starts_with("@fn")
                        || remap_directive[0].starts_with("@entry") =>
                {
                    // ???, let another phase handle
                    if remap_directive.len() < 2 {
                        output.push(remap_directive.join(" "));
                    }

                    let remap_type = remap_directive[0];
                    let name = remap_directive[1];

                    // Map to the remapped name for this.
                    let remapped_name = match remap_type {
                        "@capability" => capability_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number)
                        }),

                        "@object" => object_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number)
                        }),

                        "@global" => globals_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number)
                        }),

                        "@fn" => function_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number)
                        }),

                        "@entry" => function_map.get(name).ok_or_else(|| {
                            LinkerErrorKind::UndefinedName {
                                name: name.to_string(),
                            }
                            .with_line(line_number)
                        }),

                        _ => unreachable!(),
                    };

                    // Build errors
                    let remapped_name = match remapped_name {
                        Ok(remapped_name) => remapped_name,
                        Err(error) => {
                            errors.push(error);
                            continue;
                        }
                    };

                    let mut new_directive = (*remap_directive).to_vec();
                    new_directive[1] = &remapped_name;

                    output.push(format!("{}", new_directive.join(" ")));
                }

                // These are already consumed earlier, we ignore them now
                consumed
                    if consumed[0].starts_with("@namespace")
                        || consumed[0].starts_with("@required") => {}

                // We leave all other remapping to after all files have remapped their top level elements.
                other => output.push(other.join(" ")),
            }
        }

        file.file_contents = output.join("\n");

        // Add all these remapped symbols to the list of valid symbols
        valid_map.extend(
            globals_map
                .into_values()
                .chain(capability_map.into_values())
                .chain(function_map.into_values())
                .chain(object_map.into_values()),
        );

        if errors.len() == 0 {
            return Ok(());
        }

        Err(errors)
    }

    /// Collects all the namespaces from all files and prevents duplicates.
    fn collect_namespaces(&mut self) -> Result<(), LinkerError> {
        for file in &mut self.sources {
            let namespace = Linker::find_namespace(file)?;

            // Check for duplicates
            if self.namespaces.contains(&namespace) {
                let original = self
                    .namespace_map
                    .get(&namespace)
                    .expect("expected namespace map and namespaces to be synced");
                return Err(LinkerErrorKind::DuplicateNamespace {
                    namespace: namespace.0,
                    file_a: original.clone(),
                    file_b: file.full_file_name.clone(),
                }
                .with_line(0));
            }

            // Add to maps
            self.namespaces.insert(namespace.clone());
            self.namespace_map
                .insert(namespace, file.full_file_name.clone());
        }

        Ok(())
    }

    /// Checks that all requires in all files are declared
    fn check_all_requires(&self) -> Result<(), Vec<LinkerError>> {
        let mut errors = Vec::new();

        // Check on each file that the requires are declared
        for file in &self.sources {
            if let Err(this_errors) = self.check_requires(file) {
                errors.extend(this_errors);
            }
        }

        if errors.len() == 0 {
            return Ok(());
        }

        Err(errors)
    }

    /// Checks that all requires in a file are declared
    /// in the `namespaces`
    fn check_requires(&self, file: &LinkableFile) -> Result<(), Vec<LinkerError>> {
        let mut errors = Vec::new();

        for (line_number, line) in file.file_contents.lines().enumerate() {
            let line_number = line_number + 1;

            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            // Search for the requires directive in the file.
            match tokens.as_slice() {
                ["@requires", namespace] => {
                    // Make sure the namespace is defined.
                    if !self.namespaces.contains(&NameSpace(namespace.to_string())) {
                        errors.push(
                            LinkerErrorKind::NamespaceNotFound {
                                namespace: namespace.to_string(),
                                file_requires: file.full_file_name.clone(),
                            }
                            .with_line(line_number),
                        );
                    }
                }

                _ => {}
            }
        }

        if errors.len() == 0 {
            return Ok(());
        }

        Err(errors)
    }

    /// Finds the namespace used for a file
    fn find_namespace(file: &mut LinkableFile) -> Result<NameSpace, LinkerError> {
        let mut found_namespace = None;

        for line in file.file_contents.lines() {
            // Strip the comment from a line and ignore if empty, this means
            // we only parse actual tokens
            let line = strip_comment(line).trim();

            if line.is_empty() {
                continue;
            }

            let tokens: Vec<&str> = line.split_whitespace().collect();

            // Search for the namespace directive in the file.
            match tokens.as_slice() {
                ["@namespace", namespace] => {
                    if found_namespace.is_none() {
                        let namespace = Some(NameSpace(namespace.to_string()));
                        found_namespace = namespace.clone();
                        file.namespace = namespace;
                    } else {
                        return Err(LinkerErrorKind::MoreThanOneNamespace {
                            file: file.full_file_name.clone(),
                        }
                        .with_line(0));
                    }
                }

                _ => {}
            }
        }

        found_namespace.ok_or_else(|| {
            LinkerErrorKind::UndeclaredNamespace {
                file: file.full_file_name.clone(),
            }
            .with_line(0)
        })
    }

    /// Inserts a @loc directive at the current position with the source
    /// being the original boson3 file
    fn insert_loc(&mut self, filename: &str, line_number: usize) {
        self.output
            .push(format!("@loc {} {line_number} 0", filename))
    }

    fn push_out(&mut self, file_name: &str, contents: String, line_number: usize) {
        self.insert_loc(file_name, line_number);
        self.output.push(contents);
    }
}

/// Strip a line comment from a line
fn strip_comment(line: &str) -> &str {
    if let Some(idx) = line.find("//") {
        &line[..idx]
    } else {
        line
    }
}

impl LinkerErrorKind {
    /// Adds a line to this `LinkerErrorKind` turning it into a
    /// `LinkerError`.
    pub fn with_line(self, line_number: usize) -> LinkerError {
        LinkerError {
            line: line_number,
            kind: self,
        }
    }
}

impl Display for LinkerErrorKind {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::UndefinedName { name } => {
                write!(f, "An undefined name was referenced: `{name}`")
            }
            Self::DuplicateNamespace {
                namespace,
                file_a,
                file_b,
            } => {
                write!(
                    f,
                    "The duplicate namespace `{namespace}` was declared in both `{file_a}` and `{file_b}`"
                )
            }
            Self::MoreThanOneNamespace { file } => {
                write!(
                    f,
                    "The file `{file}` contains more than one namespace declaration"
                )
            }
            Self::UndeclaredNamespace { file } => {
                write!(f, "The file `{file}` did not declare a namespace")
            }
            Self::NamespaceNotFound {
                namespace,
                file_requires,
            } => {
                write!(
                    f,
                    "The file `{file_requires}` @requires the namespace `{namespace}` but it was not found"
                )
            }
        }
    }
}

impl Display for LinkerError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "line `{}`: {}", self.line, self.kind)
    }
}
