//! Mapping of the "long" textual version of instructions
//! which should all be descriptive

use lepton3::Opcode;

map_opcode! {
    "push.int" = Opcode::PushInt,
    "push.float" = Opcode::PushFloat,
    "push.bool" = Opcode::PushBool,
    "push.unit" = Opcode::PushUnit,
    "duplicate" = Opcode::Duplicate,
    "pop" = Opcode::Pop,
    "swap" = Opcode::Swap,
    "int.add" = Opcode::Add,
    "int.sub" = Opcode::Sub,
    "int.mul" = Opcode::Mul,
    "int.div" = Opcode::Div,
    "int.mod" = Opcode::Mod,
    "int.neg" = Opcode::Neg,
    "shift.left" = Opcode::ShiftL,
    "shift.right" = Opcode::ShiftR,
    "bitwise.and" = Opcode::And,
    "bitwise.or" = Opcode::Or,
    "bitwise.xor" = Opcode::Xor,
    "bitwise.not" = Opcode::Not,
    "int.equal" = Opcode::Equal,
    "int.not.equal" = Opcode::NotEqual,
    "int.less.than" = Opcode::LessThan,
    "int.less.than.equal" = Opcode::LessThanEq,
    "int.greater.than" = Opcode::GreaterThan,
    "int.greater.than.equal" = Opcode::GreaterThanEq,
    "bool.and" = Opcode::BoolAnd,
    "bool.or" = Opcode::BoolOr,
    "bool.not" = Opcode::BoolNot,
    "jump" = Opcode::Jump,
    "jump.if.true" = Opcode::JumpIfTrue,
    "jump.if.false" = Opcode::JumpIfFalse,
    "call" = Opcode::Call,
    "tail.call" = Opcode::TailCall,
    "return" = Opcode::Return,
    "abort" = Opcode::Abort,
    "load" = Opcode::Load,
    "store" = Opcode::Store,
    "array.new" = Opcode::ArrayNew,
    "array.cons" = Opcode::ArrayCons,
    "array.head" = Opcode::ArrayHead,
    "array.tail" = Opcode::ArrayTail,
    "array.length" = Opcode::ArrayLength,
    "array.nth" = Opcode::ArrayNth,
    "array.append" = Opcode::ArrayAppend,
    "object.new" = Opcode::ObjectNew,
    "object.set" = Opcode::ObjectSet,
    "object.get" = Opcode::ObjectGet,
    "object.length" = Opcode::ObjectLength,
    "tag.equal" = Opcode::TagEq,
    "tag.new" = Opcode::TagNew,
    "call.cap" = Opcode::CallCap,
    "try" = Opcode::Try,
    "end.try" = Opcode::EndTry,
    "raise" = Opcode::Raise,
    "float.add" = Opcode::FAdd,
    "float.sub" = Opcode::FSub,
    "float.mul" = Opcode::FMul,
    "float.div" = Opcode::FDiv,
    "float.mod" = Opcode::FMod,
    "float.neg" = Opcode::FNeg,
    "float.equal" = Opcode::FEqual,
    "float.not.equal" = Opcode::FNotEqual,
    "float.less.than" = Opcode::FLessThan,
    "float.less.than.equal" = Opcode::FLessThanEq,
    "float.greater.than" = Opcode::FGreaterThan,
    "float.greater.than.eq" = Opcode::FGreaterThanEq,
    "float.is.nan" = Opcode::FIsNaN,
    "int.to.float" = Opcode::IntToFloat,
    "float.to.int" = Opcode::FloatToInt,
    "type.of" = Opcode::TypeOf,
}
