//! Mapping of the "short" textual version of instructions
//! which should all be three characters long.

use lepton3::Opcode;

map_opcode! {
    "pin" = Opcode::PushInt,
    "pfl" = Opcode::PushFloat,
    "pbl" = Opcode::PushBool,
    "pun" = Opcode::PushUnit,
    "dup" = Opcode::Duplicate,
    "pop" = Opcode::Pop,
    "swp" = Opcode::Swap,
    "iad" = Opcode::Add,
    "isb" = Opcode::Sub,
    "iml" = Opcode::Mul,
    "idv" = Opcode::Div,
    "imd" = Opcode::Mod,
    "ing" = Opcode::Neg,
    "shl" = Opcode::ShiftL,
    "shr" = Opcode::ShiftR,
    "and" = Opcode::And,
    "orr" = Opcode::Or,
    "xor" = Opcode::Xor,
    "not" = Opcode::Not,
    "ieq" = Opcode::Equal,
    "inq" = Opcode::NotEqual,
    "ilt" = Opcode::LessThan,
    "ile" = Opcode::LessThanEq,
    "igt" = Opcode::GreaterThan,
    "ige" = Opcode::GreaterThanEq,
    "ban" = Opcode::BoolAnd,
    "bor" = Opcode::BoolOr,
    "bnt" = Opcode::BoolNot,
    "jmp" = Opcode::Jump,
    "jit" = Opcode::JumpIfTrue,
    "jif" = Opcode::JumpIfFalse,
    "cal" = Opcode::Call,
    "tcl" = Opcode::TailCall,
    "ret" = Opcode::Return,
    "abt" = Opcode::Abort,
    "lod" = Opcode::Load,
    "ste" = Opcode::Store,
    "anw" = Opcode::ArrayNew,
    "acs" = Opcode::ArrayCons,
    "ahd" = Opcode::ArrayHead,
    "atl" = Opcode::ArrayTail,
    "aln" = Opcode::ArrayLength,
    "nth" = Opcode::ArrayNth,
    "aap" = Opcode::ArrayAppend,
    "onw" = Opcode::ObjectNew,
    "ost" = Opcode::ObjectSet,
    "ogt" = Opcode::ObjectGet,
    "oln" = Opcode::ObjectLength,
    "teq" = Opcode::TagEq,
    "tnw" = Opcode::TagNew,
    "cap" = Opcode::CallCap,
    "try" = Opcode::Try,
    "etr" = Opcode::EndTry,
    "rse" = Opcode::Raise,
    "fad" = Opcode::FAdd,
    "fsb" = Opcode::FSub,
    "fml" = Opcode::FMul,
    "fdv" = Opcode::FDiv,
    "fmd" = Opcode::FMod,
    "fng" = Opcode::FNeg,
    "feq" = Opcode::FEqual,
    "fnq" = Opcode::FNotEqual,
    "flt" = Opcode::FLessThan,
    "fte" = Opcode::FLessThanEq,
    "fgt" = Opcode::FGreaterThan,
    "fge" = Opcode::FGreaterThanEq,
    "fin" = Opcode::FIsNaN,
    "itf" = Opcode::IntToFloat,
    "fti" = Opcode::FloatToInt,
    "tof" = Opcode::TypeOf,
}